/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.java.ws.panels;

import eni.m1.java.ws.entities.Bulletin;
import eni.m1.java.ws.entities.Ligne;
import eni.m1.java.ws.entities.Utilisateur;
import eni.m1.java.ws.service.BulletinService;
import eni.m1.java.ws.service.RegistreService;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shirleyodon
 */
public class BulletinPanel extends javax.swing.JPanel {

    /**
     * Creates new form BulletinPanel
     */
    
    private DefaultTableModel model;
    private BulletinService service;
    private RegistreService registreService;
    private final Utilisateur profile;
    
    public BulletinPanel(Utilisateur user) {
        initComponents();
        initTableGrid();
        initModel();
        initService();
        profile=user;
    }
    
    private void initTableGrid(){
        listeNotesTable.setGridColor(Color.lightGray);
        listeNotesTable.setShowGrid(true);
    }
    
    private void initModel(){
        model=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        model.addColumn("Désignation");
        model.addColumn("Coefficient");
        model.addColumn("Note");
        model.addColumn("Note Pondérée");
    }
    
    private void fillModel(Bulletin bulletin){
        model.setRowCount(0);
        for(Ligne ligne: bulletin.getLignes()){
            model.addRow(new Object[]{
                ligne.getLibelle(),
                ligne.getCoef(),
                ligne.getNote(),
                ligne.getNotePonderee()
            });
        }
        listeNotesTable.setModel(model);
    }
    
    private void fillFields(Bulletin bulletin){
        numEtudiantField.setText(bulletin.getEtudiant().getNumEtudiant());
        nomField.setText(bulletin.getEtudiant().getNom());
        prenomField.setText(bulletin.getEtudiant().getPrenom());
        niveauField.setText(bulletin.getEtudiant().getNiveau());
        moyenneField.setText(String.valueOf(bulletin.getMoyenne()));
        observationField.setText(bulletin.getObservation());
    }
    
    private void initService(){
        registreService=new RegistreService();
        service=new BulletinService();
    }
    
    private void genererBulletin(Bulletin bulletin){
        fillModel(bulletin);
        fillFields(bulletin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        recherchePanel = new javax.swing.JPanel();
        numEtudiantRechercheLabel = new javax.swing.JLabel();
        numEtudiantRechercheFormattedField = new javax.swing.JFormattedTextField();
        genererBulletinButton = new javax.swing.JButton();
        infoEtudiantPanel = new javax.swing.JPanel();
        numEtudiantLabel = new javax.swing.JLabel();
        numEtudiantField = new javax.swing.JTextField();
        nomLabel = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        prenomLabel = new javax.swing.JLabel();
        prenomField = new javax.swing.JTextField();
        niveauLabel = new javax.swing.JLabel();
        niveauField = new javax.swing.JTextField();
        listeNotesPanel = new javax.swing.JPanel();
        listeNotesScrollPane = new javax.swing.JScrollPane();
        listeNotesTable = new javax.swing.JTable();
        conclusionNotePanel = new javax.swing.JPanel();
        moyenneLabel = new javax.swing.JLabel();
        moyenneField = new javax.swing.JTextField();
        observationLabel = new javax.swing.JLabel();
        observationField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(44, 62, 80));
        setMaximumSize(new java.awt.Dimension(642, 544));
        setMinimumSize(new java.awt.Dimension(640, 542));

        bodyPanel.setBackground(new java.awt.Color(44, 62, 80));

        recherchePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECHERCHE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 20), java.awt.Color.lightGray)); // NOI18N
        recherchePanel.setOpaque(false);

        numEtudiantRechercheLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        numEtudiantRechercheLabel.setForeground(new java.awt.Color(236, 240, 241));
        numEtudiantRechercheLabel.setText("N° Etudiant");

        numEtudiantRechercheFormattedField.setBackground(new java.awt.Color(108, 122, 137));
        numEtudiantRechercheFormattedField.setForeground(new java.awt.Color(228, 241, 254));
        try {
            numEtudiantRechercheFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("E###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        numEtudiantRechercheFormattedField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numEtudiantRechercheFormattedField.setText("E001");
        numEtudiantRechercheFormattedField.setFont(new java.awt.Font("Lucida Console", 2, 18)); // NOI18N
        numEtudiantRechercheFormattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numEtudiantRechercheFormattedFieldActionPerformed(evt);
            }
        });

        genererBulletinButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        genererBulletinButton.setText("Générer bulletin");
        genererBulletinButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        genererBulletinButton.setPreferredSize(new java.awt.Dimension(80, 25));
        genererBulletinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genererBulletinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recherchePanelLayout = new javax.swing.GroupLayout(recherchePanel);
        recherchePanel.setLayout(recherchePanelLayout);
        recherchePanelLayout.setHorizontalGroup(
            recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recherchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numEtudiantRechercheLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numEtudiantRechercheFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genererBulletinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recherchePanelLayout.setVerticalGroup(
            recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recherchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(numEtudiantRechercheLabel)
                    .addComponent(numEtudiantRechercheFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genererBulletinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoEtudiantPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFO SUR L'ETUDIANT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 20), java.awt.Color.lightGray)); // NOI18N
        infoEtudiantPanel.setOpaque(false);

        numEtudiantLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        numEtudiantLabel.setForeground(new java.awt.Color(236, 240, 241));
        numEtudiantLabel.setText("N° Etudiant");

        numEtudiantField.setEditable(false);
        numEtudiantField.setBackground(new java.awt.Color(108, 122, 137));
        numEtudiantField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        numEtudiantField.setForeground(new java.awt.Color(228, 241, 254));
        numEtudiantField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nomLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(236, 240, 241));
        nomLabel.setText("Nom");

        nomField.setEditable(false);
        nomField.setBackground(new java.awt.Color(108, 122, 137));
        nomField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        nomField.setForeground(new java.awt.Color(228, 241, 254));
        nomField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        prenomLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prenomLabel.setForeground(new java.awt.Color(236, 240, 241));
        prenomLabel.setText("Prénom");

        prenomField.setEditable(false);
        prenomField.setBackground(new java.awt.Color(108, 122, 137));
        prenomField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        prenomField.setForeground(new java.awt.Color(228, 241, 254));
        prenomField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        niveauLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        niveauLabel.setForeground(new java.awt.Color(236, 240, 241));
        niveauLabel.setText("Niveau");

        niveauField.setEditable(false);
        niveauField.setBackground(new java.awt.Color(108, 122, 137));
        niveauField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        niveauField.setForeground(new java.awt.Color(228, 241, 254));
        niveauField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout infoEtudiantPanelLayout = new javax.swing.GroupLayout(infoEtudiantPanel);
        infoEtudiantPanel.setLayout(infoEtudiantPanelLayout);
        infoEtudiantPanelLayout.setHorizontalGroup(
            infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEtudiantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numEtudiantLabel)
                    .addComponent(nomLabel)
                    .addComponent(prenomLabel)
                    .addComponent(niveauLabel))
                .addGap(21, 21, 21)
                .addGroup(infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numEtudiantField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveauField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoEtudiantPanelLayout.setVerticalGroup(
            infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEtudiantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numEtudiantLabel)
                    .addComponent(numEtudiantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLabel)
                    .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoEtudiantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(niveauField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveauLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listeNotesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTE DES NOTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 20), java.awt.Color.lightGray)); // NOI18N
        listeNotesPanel.setOpaque(false);

        listeNotesTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        listeNotesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Désignation", "Coefficient", "Note", "Note Pondérée"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeNotesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listeNotesTable.setRowHeight(20);
        listeNotesTable.setShowGrid(true);
        listeNotesScrollPane.setViewportView(listeNotesTable);

        conclusionNotePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        conclusionNotePanel.setOpaque(false);

        moyenneLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        moyenneLabel.setForeground(new java.awt.Color(236, 240, 241));
        moyenneLabel.setText("Moyenne");

        moyenneField.setEditable(false);
        moyenneField.setBackground(new java.awt.Color(108, 122, 137));
        moyenneField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        moyenneField.setForeground(new java.awt.Color(228, 241, 254));
        moyenneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        moyenneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moyenneFieldActionPerformed(evt);
            }
        });

        observationLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        observationLabel.setForeground(new java.awt.Color(236, 240, 241));
        observationLabel.setText("Observation");

        observationField.setEditable(false);
        observationField.setBackground(new java.awt.Color(108, 122, 137));
        observationField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        observationField.setForeground(new java.awt.Color(228, 241, 254));
        observationField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        observationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observationFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conclusionNotePanelLayout = new javax.swing.GroupLayout(conclusionNotePanel);
        conclusionNotePanel.setLayout(conclusionNotePanelLayout);
        conclusionNotePanelLayout.setHorizontalGroup(
            conclusionNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conclusionNotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conclusionNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conclusionNotePanelLayout.createSequentialGroup()
                        .addComponent(moyenneLabel)
                        .addGap(29, 29, 29)
                        .addComponent(moyenneField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conclusionNotePanelLayout.createSequentialGroup()
                        .addComponent(observationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(observationField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        conclusionNotePanelLayout.setVerticalGroup(
            conclusionNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conclusionNotePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(conclusionNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moyenneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moyenneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(conclusionNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(observationLabel)
                    .addComponent(observationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout listeNotesPanelLayout = new javax.swing.GroupLayout(listeNotesPanel);
        listeNotesPanel.setLayout(listeNotesPanelLayout);
        listeNotesPanelLayout.setHorizontalGroup(
            listeNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeNotesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(listeNotesPanelLayout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(conclusionNotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        listeNotesPanelLayout.setVerticalGroup(
            listeNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeNotesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listeNotesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conclusionNotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoEtudiantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(listeNotesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(recherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoEtudiantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeNotesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void moyenneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moyenneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moyenneFieldActionPerformed

    private void observationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observationFieldActionPerformed

    private void numEtudiantRechercheFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numEtudiantRechercheFormattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numEtudiantRechercheFormattedFieldActionPerformed

    private void genererBulletinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genererBulletinButtonActionPerformed
        // TODO add your handling code here:
        if(numEtudiantRechercheFormattedField.isEditValid()){
            Bulletin bulletin=service.get(numEtudiantRechercheFormattedField.getText());
            
            if(bulletin.getEtudiant()==null)
                JOptionPane.showMessageDialog(null, "L'étudiant portant le n° '"+numEtudiantRechercheFormattedField.getText()+"' n'existe pas dans la base de données", "Aucun résultat", JOptionPane.ERROR_MESSAGE);
            else
                genererBulletin(bulletin);
            registreService.saveToLog(profile.getLogin(), "GENERATION BULLETIN", numEtudiantRechercheFormattedField.getText());
            numEtudiantRechercheFormattedField.setValue(null);
        }else{
            JOptionPane.showMessageDialog(null, "Le n° étudiant saisi est invalide", "Numéro invalide", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_genererBulletinButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel conclusionNotePanel;
    private javax.swing.JButton genererBulletinButton;
    private javax.swing.JPanel infoEtudiantPanel;
    private javax.swing.JPanel listeNotesPanel;
    private javax.swing.JScrollPane listeNotesScrollPane;
    private javax.swing.JTable listeNotesTable;
    private javax.swing.JTextField moyenneField;
    private javax.swing.JLabel moyenneLabel;
    private javax.swing.JTextField niveauField;
    private javax.swing.JLabel niveauLabel;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField numEtudiantField;
    private javax.swing.JLabel numEtudiantLabel;
    private javax.swing.JFormattedTextField numEtudiantRechercheFormattedField;
    private javax.swing.JLabel numEtudiantRechercheLabel;
    private javax.swing.JTextField observationField;
    private javax.swing.JLabel observationLabel;
    private javax.swing.JTextField prenomField;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JPanel recherchePanel;
    // End of variables declaration//GEN-END:variables
}
