/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.java.ws.panels;

import eni.m1.java.ws.dialog.Chart;
import eni.m1.java.ws.entities.LigneClassement;
import eni.m1.java.ws.entities.Utilisateur;
import eni.m1.java.ws.service.ClassementService;
import eni.m1.java.ws.service.RegistreService;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shirleyodon
 */
public class ClassementPanel extends javax.swing.JPanel {

    /**
     * Creates new form classementPanel
     */
    
    private DefaultTableModel model;
    private ClassementService service;
    private RegistreService registreService;
    private final Utilisateur profile;
    
    public ClassementPanel(Utilisateur user) {
        initComponents();
        initTableGrid();
        initModel();
        initService();
        profile=user;
    }
    
    private void initTableGrid(){
        etudiantTable.setGridColor(Color.lightGray);
        etudiantTable.setShowGrid(true);
    }
    
    private void initModel(){
        model=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        model.addColumn("Rang");
        model.addColumn("N° Etudiant");
        model.addColumn("Nom");
        model.addColumn("Prénom");
        model.addColumn("Moyenne");
    }
    
    private void fillModel(LigneClassement[] list) {
    	model.setRowCount(0);
    	for(LigneClassement ligne: list){
            model.addRow(
                new Object[]{
                    ligne.getRang(),
                    ligne.getNumEtudiant(),
                    ligne.getNom(),
                    ligne.getPrenom(),
                    ligne.getMoyenne()
                });
        }
    	etudiantTable.setModel(model);
    }
    
    private void initService(){
        registreService=new RegistreService();
        service=new ClassementService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        recherchePanel = new javax.swing.JPanel();
        niveauRechercheLabel = new javax.swing.JLabel();
        niveauComboBox = new javax.swing.JComboBox<>();
        ClasserButton = new javax.swing.JButton();
        listeEtudiantsPanel = new javax.swing.JPanel();
        listeEtudiantsScrollPane = new javax.swing.JScrollPane();
        etudiantTable = new javax.swing.JTable();
        chartButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 62, 80));
        setMaximumSize(new java.awt.Dimension(591, 442));
        setMinimumSize(new java.awt.Dimension(545, 440));

        bodyPanel.setBackground(new java.awt.Color(44, 62, 80));

        recherchePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECHERCHE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 20), java.awt.Color.lightGray)); // NOI18N
        recherchePanel.setOpaque(false);

        niveauRechercheLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        niveauRechercheLabel.setForeground(new java.awt.Color(236, 240, 241));
        niveauRechercheLabel.setText("Niveau");

        niveauComboBox.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        niveauComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "L3", "M1", "M2" }));
        niveauComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ClasserButton.setBackground(new java.awt.Color(108, 122, 137));
        ClasserButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ClasserButton.setForeground(new java.awt.Color(228, 241, 254));
        ClasserButton.setText("Classifier");
        ClasserButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClasserButton.setPreferredSize(new java.awt.Dimension(80, 25));
        ClasserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recherchePanelLayout = new javax.swing.GroupLayout(recherchePanel);
        recherchePanel.setLayout(recherchePanelLayout);
        recherchePanelLayout.setHorizontalGroup(
            recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recherchePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(niveauRechercheLabel)
                    .addGroup(recherchePanelLayout.createSequentialGroup()
                        .addComponent(niveauComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(ClasserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        recherchePanelLayout.setVerticalGroup(
            recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recherchePanelLayout.createSequentialGroup()
                .addComponent(niveauRechercheLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(niveauComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClasserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listeEtudiantsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTE DES ETUDIANTS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 20), java.awt.Color.lightGray)); // NOI18N
        listeEtudiantsPanel.setOpaque(false);

        etudiantTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        etudiantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rang", "N° Etudiant", "Nom", "Prénom", "Moyenne"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        etudiantTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etudiantTable.setRowHeight(20);
        etudiantTable.setShowGrid(true);
        listeEtudiantsScrollPane.setViewportView(etudiantTable);

        javax.swing.GroupLayout listeEtudiantsPanelLayout = new javax.swing.GroupLayout(listeEtudiantsPanel);
        listeEtudiantsPanel.setLayout(listeEtudiantsPanelLayout);
        listeEtudiantsPanelLayout.setHorizontalGroup(
            listeEtudiantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeEtudiantsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        listeEtudiantsPanelLayout.setVerticalGroup(
            listeEtudiantsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeEtudiantsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listeEtudiantsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        chartButton.setBackground(new java.awt.Color(34, 167, 240));
        chartButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        chartButton.setForeground(new java.awt.Color(255, 255, 255));
        chartButton.setText("Graphe de répartition");
        chartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(recherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeEtudiantsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chartButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(recherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(listeEtudiantsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chartButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClasserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasserButtonActionPerformed
        // TODO add your handling code here:
        String niveau=niveauComboBox.getSelectedItem().toString();
        fillModel(service.getAll(niveau));
        registreService.saveToLog(profile.getLogin(), "CLASSIFICATION", niveau);
    }//GEN-LAST:event_ClasserButtonActionPerformed

    private void chartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartButtonActionPerformed
        // TODO add your handling code here:
        String niveau=niveauComboBox.getSelectedItem().toString();
        Chart chart=new Chart(null, true, profile, niveau, service.getAll(niveau));
        chart.setVisible(true);
    }//GEN-LAST:event_chartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClasserButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton chartButton;
    private javax.swing.JTable etudiantTable;
    private javax.swing.JPanel listeEtudiantsPanel;
    private javax.swing.JScrollPane listeEtudiantsScrollPane;
    private javax.swing.JComboBox<String> niveauComboBox;
    private javax.swing.JLabel niveauRechercheLabel;
    private javax.swing.JPanel recherchePanel;
    // End of variables declaration//GEN-END:variables
}
