/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.java.ws.dialog;

/**
 *
 * @author shirleyodon
 */
public class AboutProject extends javax.swing.JDialog {

    /**
     * Creates new form AboutProject
     */
    public AboutProject(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        fermerLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        technologieLabel = new javax.swing.JLabel();
        technologieScrollPane = new javax.swing.JScrollPane();
        technologieTextArea = new javax.swing.JTextArea();
        ideLabel = new javax.swing.JLabel();
        ideScrollPane = new javax.swing.JScrollPane();
        ideTextArea = new javax.swing.JTextArea();
        versionLabel = new javax.swing.JLabel();
        versionScrollPane = new javax.swing.JScrollPane();
        versionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(270, 405));
        setUndecorated(true);
        setResizable(false);

        titlePanel.setBackground(new java.awt.Color(248, 148, 6));

        titleLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("A propos");

        fermerLabel.setBackground(new java.awt.Color(248, 148, 6));
        fermerLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        fermerLabel.setForeground(new java.awt.Color(255, 255, 255));
        fermerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fermerLabel.setText("X");
        fermerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fermerLabel.setOpaque(true);
        fermerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fermerLabelMouseMoved(evt);
            }
        });
        fermerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fermerLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(fermerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fermerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bodyPanel.setBackground(new java.awt.Color(44, 62, 80));

        descriptionLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(236, 240, 241));
        descriptionLabel.setText("Description");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(108, 122, 137));
        descriptionTextArea.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        descriptionTextArea.setForeground(new java.awt.Color(228, 241, 254));
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(4);
        descriptionTextArea.setTabSize(20);
        descriptionTextArea.setText("C'est une application Java de gestion de note basée sur un service Web RESTfull et consumée par un client Swing");
        descriptionTextArea.setWrapStyleWord(true);
        descriptionTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        descriptionScrollPane.setViewportView(descriptionTextArea);

        technologieLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        technologieLabel.setForeground(new java.awt.Color(236, 240, 241));
        technologieLabel.setText("Technologie utilisée");

        technologieTextArea.setEditable(false);
        technologieTextArea.setBackground(new java.awt.Color(108, 122, 137));
        technologieTextArea.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        technologieTextArea.setForeground(new java.awt.Color(228, 241, 254));
        technologieTextArea.setLineWrap(true);
        technologieTextArea.setText("JAX-RS / Jersey");
        technologieTextArea.setWrapStyleWord(true);
        technologieTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        technologieScrollPane.setViewportView(technologieTextArea);

        ideLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ideLabel.setForeground(new java.awt.Color(236, 240, 241));
        ideLabel.setText("IDE");

        ideTextArea.setEditable(false);
        ideTextArea.setBackground(new java.awt.Color(108, 122, 137));
        ideTextArea.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        ideTextArea.setForeground(new java.awt.Color(228, 241, 254));
        ideTextArea.setLineWrap(true);
        ideTextArea.setText("Eclipse (serveur)\nNetBeans (client)");
        ideTextArea.setWrapStyleWord(true);
        ideTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ideScrollPane.setViewportView(ideTextArea);

        versionLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(236, 240, 241));
        versionLabel.setText("Version");

        versionTextArea.setEditable(false);
        versionTextArea.setBackground(new java.awt.Color(108, 122, 137));
        versionTextArea.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        versionTextArea.setForeground(new java.awt.Color(228, 241, 254));
        versionTextArea.setLineWrap(true);
        versionTextArea.setText("2.0");
        versionTextArea.setWrapStyleWord(true);
        versionTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        versionScrollPane.setViewportView(versionTextArea);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(technologieLabel)
                    .addComponent(ideLabel)
                    .addComponent(versionLabel)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(technologieScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ideScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(versionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(technologieLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(technologieScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ideLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ideScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerLabelMouseMoved
        // TODO add your handling code here:
        fermerLabel.setBackground(new java.awt.Color(242,38,19));
    }//GEN-LAST:event_fermerLabelMouseMoved

    private void fermerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_fermerLabelMouseClicked

    private void fermerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerLabelMouseExited
        // TODO add your handling code here:
        fermerLabel.setBackground(new java.awt.Color(248,148,6));
    }//GEN-LAST:event_fermerLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutProject dialog = new AboutProject(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel fermerLabel;
    private javax.swing.JLabel ideLabel;
    private javax.swing.JScrollPane ideScrollPane;
    private javax.swing.JTextArea ideTextArea;
    private javax.swing.JLabel technologieLabel;
    private javax.swing.JScrollPane technologieScrollPane;
    private javax.swing.JTextArea technologieTextArea;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JScrollPane versionScrollPane;
    private javax.swing.JTextArea versionTextArea;
    // End of variables declaration//GEN-END:variables
}
