/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.java.ws.dialog;

import eni.m1.java.ws.entities.Utilisateur;
import eni.m1.java.ws.service.ProfilService;
import eni.m1.java.ws.service.RegistreService;
import javax.swing.JOptionPane;

/**
 *
 * @author shirleyodon
 */
public class NewProfile extends javax.swing.JDialog {

    /**
     * Creates new form NewProfile
     */
    
    private final Utilisateur currentProfile;
    private Utilisateur createdProfile;
    private final ProfilService service;
    private final RegistreService registreService;
    
    public NewProfile(java.awt.Frame parent, boolean modal, Utilisateur user) {
        super(parent, modal);
        initComponents();
        service=new ProfilService();
        registreService=new RegistreService();
        currentProfile=user;
        createdProfile=new Utilisateur();
        this.setLocationRelativeTo(null);
    }
    
    private boolean estVide(javax.swing.JTextField field){
        return field.getText().equals("");
    }
    
    public Utilisateur afficher(){
        setVisible(true);
        return createdProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        fermerLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();
        eyeLabel = new javax.swing.JLabel();
        statutLabel = new javax.swing.JLabel();
        statutComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        titlePanel.setBackground(new java.awt.Color(248, 148, 6));

        titleLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Nouvel utilisateur");

        fermerLabel.setBackground(new java.awt.Color(248, 148, 6));
        fermerLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        fermerLabel.setForeground(new java.awt.Color(255, 255, 255));
        fermerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fermerLabel.setText("X");
        fermerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fermerLabel.setOpaque(true);
        fermerLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fermerLabelMouseMoved(evt);
            }
        });
        fermerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fermerLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(fermerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(fermerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
        );

        bodyPanel.setBackground(new java.awt.Color(44, 62, 80));

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(236, 240, 241));
        nameLabel.setText("Nom");

        nameField.setBackground(new java.awt.Color(108, 122, 137));
        nameField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        nameField.setForeground(new java.awt.Color(228, 241, 254));
        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        firstNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(236, 240, 241));
        firstNameLabel.setText("Prénom");

        firstNameField.setBackground(new java.awt.Color(108, 122, 137));
        firstNameField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(228, 241, 254));
        firstNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loginLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(236, 240, 241));
        loginLabel.setText("Login");

        loginField.setBackground(new java.awt.Color(108, 122, 137));
        loginField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        loginField.setForeground(new java.awt.Color(228, 241, 254));
        loginField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pwdLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        pwdLabel.setForeground(new java.awt.Color(236, 240, 241));
        pwdLabel.setText("Mot de passe");

        pwdField.setBackground(new java.awt.Color(108, 122, 137));
        pwdField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        pwdField.setForeground(new java.awt.Color(228, 241, 254));
        pwdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eyeLabel.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        eyeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eyeLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\26134\\Documents\\NetBeansProjects\\GradeManagementCLIENT2\\src\\main\\java\\eni\\m1\\java\\ws\\icons\\eye.png")); // NOI18N
        eyeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyeLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eyeLabelMouseReleased(evt);
            }
        });

        statutLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        statutLabel.setForeground(new java.awt.Color(236, 240, 241));
        statutLabel.setText("Statut");

        statutComboBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        statutComboBox.setForeground(new java.awt.Color(44, 62, 80));
        statutComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Root", "User", "Visitor" }));
        statutComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cancelButton.setBackground(new java.awt.Color(242, 38, 19));
        cancelButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(34, 167, 240));
        createButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Créer");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdLabel)
                            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(eyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(191, 191, 191))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(statutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 203, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(33, 33, 33)
                .addComponent(createButton)
                .addGap(52, 52, 52))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(loginLabel))
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pwdLabel)))
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(statutLabel))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(statutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(cancelButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerLabelMouseMoved
        // TODO add your handling code here:
        fermerLabel.setBackground(new java.awt.Color(242,38,19));
    }//GEN-LAST:event_fermerLabelMouseMoved

    private void fermerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_fermerLabelMouseClicked

    private void fermerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerLabelMouseExited
        // TODO add your handling code here:
        fermerLabel.setBackground(new java.awt.Color(248,148,6));
    }//GEN-LAST:event_fermerLabelMouseExited

    private void eyeLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeLabelMousePressed
        // TODO add your handling code here:
        pwdField.setEchoChar('\u0000');
    }//GEN-LAST:event_eyeLabelMousePressed

    private void eyeLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeLabelMouseReleased
        // TODO add your handling code here:
        pwdField.setEchoChar('*');
    }//GEN-LAST:event_eyeLabelMouseReleased

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Voullez-vous vraiment abandonner la création du nouvel utilisateur ?", "Confirmation d'annulation",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(estVide(nameField) || estVide(firstNameField) || estVide(loginField) || estVide(pwdField)){
            JOptionPane.showMessageDialog(null, "Au moins un des champs est laissé vide", "Champ(s) vide(s)", JOptionPane.WARNING_MESSAGE);
        }else{
            String pwd=new String();

            for(char kter: pwdField.getPassword())
                pwd+=kter;

            Utilisateur newProfile=new Utilisateur(nameField.getText(), firstNameField.getText(), loginField.getText(), pwd, statutComboBox.getSelectedItem().toString());

            Integer added=service.post(newProfile);
            
            switch(added){
                case -1:
                    JOptionPane.showMessageDialog(null, "Le même login '"+loginField.getText()+"' est déjà utilisé par un autre utilisateur, veuillez le changer", "Duplication de login", JOptionPane.ERROR_MESSAGE);
                    break;
                case 1:
                    String message="L'utilisateur :\n"
                                    +"\tNom = '"+newProfile.getNom()+"'\n"
                                    +"\tPrénom = '"+newProfile.getPrenom()+"'\n"
                                    +"\tLogin = '"+newProfile.getLogin()+"'\n"
                                    +"\tMot de passe = '"+newProfile.getPwd()+"'\n"
                                    +"\tStatut = '"+newProfile.getStatut()+"'\n"
                                +"a été ajouté avec succès";
                    JOptionPane.showMessageDialog(null, message, "Succès de création", JOptionPane.INFORMATION_MESSAGE);
                    registreService.saveToLog(currentProfile.getLogin(), "AJOUT", newProfile.getLogin());
                    createdProfile=newProfile;
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Echec de la création du nouveau compte utilisateur", "Erreur de création", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewProfile dialog = new NewProfile(new javax.swing.JFrame(), true, new Utilisateur());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel eyeLabel;
    private javax.swing.JLabel fermerLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JComboBox<String> statutComboBox;
    private javax.swing.JLabel statutLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
