/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.java.ws.frame;

import eni.m1.java.ws.dialog.*;
import eni.m1.java.ws.entities.Utilisateur;
import eni.m1.java.ws.panels.*;
import eni.m1.java.ws.service.RegistreService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shirleyodon
 */
public class ManagementClient2 extends javax.swing.JFrame {

    /**
     * Creates new form ManagementClient2
     */
    
    private Utilisateur profile;
    private final RegistreService registreService;
    
    public ManagementClient2(Utilisateur profile) {
        initComponents();
        this.profile=profile;
        registreService=new RegistreService();
        parameters();
        initTabbedPane();
        this.setLocationRelativeTo(null);
    }
    
    private String setTabGap(String name, int gap){
        String space="";
        for(int i=0; i<gap; i++)
            space+=" ";
        return space+name+space;
    }
    
    private void initTabbedPane(){
        List<JPanel> listPanel=new ArrayList<>();
        listPanel.add(new EtudiantPanel(profile));
        listPanel.add(new MatierePanel(profile));
        listPanel.add(new NotePanel(profile));
        listPanel.add(new BulletinPanel(profile));
        listPanel.add(new ClassementPanel(profile));
        
        String nomOnglet[]={"Etudiants", "Matières", "Notes", "Bulletin", "Classement"};
        for(int i=0; i<listPanel.size(); i++)
            onglets.add(setTabGap(nomOnglet[i], 7), listPanel.get(i));
    }
    
    private void parameters(){
        if(!profile.getStatut().equals("Root")){
            allUsersItem.setEnabled(false);
            logItem.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onglets = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        profileItem = new javax.swing.JMenuItem();
        allUsersItem = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        logItem = new javax.swing.JMenuItem();
        separator2 = new javax.swing.JPopupMenu.Separator();
        logoutItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        menuPlusInfo = new javax.swing.JMenu();
        aboutProjectItem = new javax.swing.JMenuItem();
        teamMembersItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRADE MANAGEMENT");
        setPreferredSize(new java.awt.Dimension(803, 643));
        setResizable(false);

        onglets.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        menuBar.setForeground(new java.awt.Color(236, 240, 241));
        menuBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(97, 30));

        menuFichier.setBackground(new java.awt.Color(248, 148, 6));
        menuFichier.setForeground(new java.awt.Color(255, 255, 255));
        menuFichier.setText("Fichier");
        menuFichier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuFichier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuFichier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuFichier.setIconTextGap(10);
        menuFichier.setOpaque(true);
        menuFichier.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menuFichierMouseMoved(evt);
            }
        });
        menuFichier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFichierMouseExited(evt);
            }
        });

        profileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        profileItem.setBackground(new java.awt.Color(44, 62, 80));
        profileItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        profileItem.setForeground(new java.awt.Color(236, 240, 241));
        profileItem.setText("Voir mon profil");
        profileItem.setOpaque(true);
        profileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileItemActionPerformed(evt);
            }
        });
        menuFichier.add(profileItem);

        allUsersItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        allUsersItem.setBackground(new java.awt.Color(44, 62, 80));
        allUsersItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        allUsersItem.setForeground(new java.awt.Color(236, 240, 241));
        allUsersItem.setText("Liste des utilisateurs");
        allUsersItem.setOpaque(true);
        allUsersItem.setPreferredSize(new java.awt.Dimension(250, 26));
        allUsersItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allUsersItemActionPerformed(evt);
            }
        });
        menuFichier.add(allUsersItem);

        separator.setBackground(new java.awt.Color(44, 62, 80));
        menuFichier.add(separator);

        logItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        logItem.setBackground(new java.awt.Color(44, 62, 80));
        logItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logItem.setForeground(new java.awt.Color(236, 240, 241));
        logItem.setText("Régistres");
        logItem.setOpaque(true);
        logItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logItemActionPerformed(evt);
            }
        });
        menuFichier.add(logItem);
        menuFichier.add(separator2);

        logoutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        logoutItem.setBackground(new java.awt.Color(44, 62, 80));
        logoutItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logoutItem.setForeground(new java.awt.Color(236, 240, 241));
        logoutItem.setText("Déconnexion");
        logoutItem.setOpaque(true);
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        menuFichier.add(logoutItem);

        exitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exitItem.setBackground(new java.awt.Color(44, 62, 80));
        exitItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        exitItem.setForeground(new java.awt.Color(236, 240, 241));
        exitItem.setText("Quitter");
        exitItem.setOpaque(true);
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        menuFichier.add(exitItem);

        menuBar.add(menuFichier);

        menuPlusInfo.setBackground(new java.awt.Color(248, 148, 6));
        menuPlusInfo.setForeground(new java.awt.Color(255, 255, 255));
        menuPlusInfo.setText("   ?");
        menuPlusInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuPlusInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuPlusInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuPlusInfo.setIconTextGap(10);
        menuPlusInfo.setOpaque(true);
        menuPlusInfo.setPreferredSize(new java.awt.Dimension(40, 21));
        menuPlusInfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menuPlusInfoMouseMoved(evt);
            }
        });
        menuPlusInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPlusInfoMouseExited(evt);
            }
        });

        aboutProjectItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        aboutProjectItem.setBackground(new java.awt.Color(44, 62, 80));
        aboutProjectItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aboutProjectItem.setForeground(new java.awt.Color(236, 240, 241));
        aboutProjectItem.setText("A propos");
        aboutProjectItem.setOpaque(true);
        aboutProjectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutProjectItemActionPerformed(evt);
            }
        });
        menuPlusInfo.add(aboutProjectItem);

        teamMembersItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        teamMembersItem.setBackground(new java.awt.Color(44, 62, 80));
        teamMembersItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        teamMembersItem.setForeground(new java.awt.Color(236, 240, 241));
        teamMembersItem.setText("Membres du groupe");
        teamMembersItem.setOpaque(true);
        teamMembersItem.setPreferredSize(new java.awt.Dimension(250, 26));
        teamMembersItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamMembersItemActionPerformed(evt);
            }
        });
        menuPlusInfo.add(teamMembersItem);

        menuBar.add(menuPlusInfo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onglets, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onglets, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFichierMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFichierMouseMoved
        // TODO add your handling code here:
        menuFichier.setBackground(new java.awt.Color(245, 103, 27));
    }//GEN-LAST:event_menuFichierMouseMoved

    private void menuFichierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFichierMouseExited
        // TODO add your handling code here:
        menuFichier.setBackground(new java.awt.Color(248,148,6));
    }//GEN-LAST:event_menuFichierMouseExited

    private void menuPlusInfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlusInfoMouseMoved
        // TODO add your handling code here:
        menuPlusInfo.setBackground(new java.awt.Color(245, 103, 27));
    }//GEN-LAST:event_menuPlusInfoMouseMoved

    private void menuPlusInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlusInfoMouseExited
        // TODO add your handling code here:
        menuPlusInfo.setBackground(new java.awt.Color(248,148,6));
    }//GEN-LAST:event_menuPlusInfoMouseExited

    private void allUsersItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allUsersItemActionPerformed
        // TODO add your handling code here:
        ListProfiles viewAllProfiles=new ListProfiles(null, true, profile);
        profile=viewAllProfiles.afficher();
        if(profile.getLogin()==null){
            Authentification authen= new Authentification();
            authen.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_allUsersItemActionPerformed

    private void profileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileItemActionPerformed
        // TODO add your handling code here:
        Profile viewProfile=new Profile(null, true, profile, profile);
        profile=viewProfile.afficher();
        parameters();
    }//GEN-LAST:event_profileItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment vous déconnecter ?", "Confirmation de déconnexion",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
            Authentification authen= new Authentification();
            authen.setVisible(true);
            registreService.saveToLog(profile.getLogin(), "DECONNEXION", "-");
            dispose();
        }
    }//GEN-LAST:event_logoutItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Etes-vous sûr de vouloir quitter l'application ?", "Confirmation de fermeture",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
            registreService.saveToLog(profile.getLogin(), "EXIT", "-");
            System.exit(0);
        }
    }//GEN-LAST:event_exitItemActionPerformed

    private void aboutProjectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutProjectItemActionPerformed
        // TODO add your handling code here:
        AboutProject aboutProject=new AboutProject(null, true);
        aboutProject.setVisible(true);
    }//GEN-LAST:event_aboutProjectItemActionPerformed

    private void teamMembersItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamMembersItemActionPerformed
        // TODO add your handling code here:
        TeamMembers viewTeamMembers=new TeamMembers(null, true);
        viewTeamMembers.setVisible(true);
    }//GEN-LAST:event_teamMembersItemActionPerformed

    private void logItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logItemActionPerformed
        // TODO add your handling code here:
        Log registre=new Log(null, true);
        registre.setVisible(true);
    }//GEN-LAST:event_logItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Utilisateur user=new Utilisateur("TAFITA","Shirley","Root#","root@ws.project","Root");
                new ManagementClient2(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutProjectItem;
    private javax.swing.JMenuItem allUsersItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenuItem logItem;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenu menuPlusInfo;
    private javax.swing.JTabbedPane onglets;
    private javax.swing.JMenuItem profileItem;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JPopupMenu.Separator separator2;
    private javax.swing.JMenuItem teamMembersItem;
    // End of variables declaration//GEN-END:variables
}
